# Generated by Django 6.0.6 on 2026-08-01 07:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0003_initial'),
        ('students', '0002_initial'),
        ('teachers', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('attendance_date', models.DateField(default=django.utils.timezone.now)),
                ('present', models.BooleanField()),
                ('reason_if_absent', models.TextField(blank=True, null=True)),
                ('synced', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.student')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='teachers.teacher')),
            ],
            options={
                'db_table': 'attendances',
            },
        ),
        migrations.CreateModel(
            name='AttendanceSyncEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('local_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('attendance_date', models.DateField()),
                ('present', models.BooleanField()),
                ('reason_if_absent', models.TextField(blank=True, null=True)),
                ('source', models.CharField(choices=[('local', 'Saisie hors-ligne'), ('remote', 'Saisie en ligne')], max_length=10)),
                ('local_timestamp', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'En attente de traitement'), ('applied', 'Appliquée sans conflit'), ('conflict', 'En conflit'), ('discarded', 'Écartée (doublon idempotent)')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.teacher')),
            ],
            options={
                'db_table': 'attendance_sync_entries',
            },
        ),
        migrations.CreateModel(
            name='AttendanceConflict',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('local_version', models.JSONField()),
                ('remote_version', models.JSONField()),
                ('resolution_choice', models.CharField(blank=True, choices=[('local', 'Garder la version locale'), ('remote', 'Garder la version distante'), ('manual_merge', "Décision manuelle de l'admin")], max_length=15, null=True)),
                ('resolved_present', models.BooleanField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='attendances.attendance')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sync_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conflict', to='attendances.attendancesyncentry')),
            ],
            options={
                'db_table': 'attendance_conflicts',
            },
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['course', 'attendance_date'], name='attendances_course__2f365f_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['synced'], name='attendances_synced_24c811_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('student', 'course', 'attendance_date'), name='uniq_attendance_per_student_course_date'),
        ),
        migrations.AddIndex(
            model_name='attendancesyncentry',
            index=models.Index(fields=['status'], name='attendance__status_55f00c_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesyncentry',
            index=models.Index(fields=['course', 'attendance_date'], name='attendance__course__388005_idx'),
        ),
    ]
