# Generated by Django 6.0.6 on 2026-08-01 06:48

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('contract', 'Contrat'), ('salary', 'Salaire'), ('leave', 'Congé'), ('evaluation', 'Évaluation'), ('hr_document', 'Document RH')], max_length=20)),
                ('entity_id', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('approve', 'Approbation'), ('reject', 'Rejet')], max_length=20)),
                ('changes_json', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('action_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Audit log RH',
                'verbose_name_plural': 'Audit logs RH',
                'ordering': ['-action_at'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('permanent', 'Permanent'), ('temporary', 'Temporaire'), ('part_time', 'Temps partiel'), ('consultant', 'Consultant')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('monthly_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('HTG', 'Gourde haïtienne'), ('USD', 'Dollar américain')], default='HTG', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('active', 'Actif'), ('expired', 'Expiré'), ('terminated', 'Résilié')], default='draft', max_length=20)),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='hr/contracts/')),
                ('notice_period_days', models.PositiveIntegerField(default=30)),
                ('termination_reason', models.TextField(blank=True)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='HRDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('diploma', 'Diplôme'), ('certification', 'Certification'), ('license', "Licence d'enseignement"), ('id_card', "Pièce d'identité"), ('cv', 'CV'), ('other', 'Autre')], max_length=20)),
                ('filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='hr/documents/')),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('valid', 'Valide'), ('expiring_soon', 'Expire bientôt'), ('expired', 'Expiré')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days_used', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='hr/leave_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('days_per_year', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_paid', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_date', models.DateField()),
                ('evaluation_period_start', models.DateField(blank=True, null=True)),
                ('evaluation_period_end', models.DateField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('1')), django.core.validators.MaxValueValidator(Decimal('5'))])),
                ('criteria_scores', models.JSONField(blank=True, default=dict)),
                ('strengths', models.TextField(blank=True)),
                ('areas_for_improvement', models.TextField(blank=True)),
                ('evaluation_type', models.CharField(choices=[('annual', 'Annuelle'), ('probation', "Fin de période d'essai"), ('disciplinary', 'Disciplinaire'), ('ad_hoc', 'Ponctuelle')], max_length=20)),
                ('teacher_acknowledged', models.BooleanField(default=False)),
                ('teacher_comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-evaluation_date'],
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_period_start', models.DateField()),
                ('pay_period_end', models.DateField()),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonuses', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours de traitement'), ('paid', 'Payé'), ('bounced', 'Rejeté'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('payslip_file', models.FileField(blank=True, null=True, upload_to='hr/payslips/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-pay_period_start'],
            },
        ),
    ]
