# Generated by Django 6.0.6 on 2026-08-06 03:29

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('position', models.CharField(max_length=150)),
                ('application_date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('interview', 'Entretien'), ('selected', 'Sélectionné'), ('rejected', 'Rejeté'), ('hired', 'Embauché')], default='pending', max_length=20)),
                ('interview_date', models.DateField(blank=True, null=True)),
                ('interview_time', models.TimeField(blank=True, null=True)),
                ('interviewer', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='hr/candidates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-application_date', 'last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('job_title', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=150)),
                ('hire_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Actif'), ('suspended', 'Suspendu'), ('inactive', 'Inactif'), ('terminated', 'Fin de contrat')], default='active', max_length=20)),
                ('monthly_salary', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('monthly_bonus', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='entity_type',
            field=models.CharField(choices=[('employee', 'Employé'), ('candidate', 'Candidat'), ('attendance', 'Présence'), ('contract', 'Contrat'), ('salary', 'Salaire'), ('leave', 'Congé'), ('evaluation', 'Évaluation'), ('hr_document', 'Document RH')], max_length=20),
        ),
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('present', 'Présent'), ('late', 'Retard'), ('absent', 'Absent'), ('excused', 'Absence justifiée')], default='present', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='hr.employee')),
            ],
            options={
                'ordering': ['-date', 'employee__last_name'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'date'), name='hr_one_attendance_per_employee_day')],
            },
        ),
    ]
