# Generated by Django 6.0.6 on 2026-08-07 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_candidate_employee_alter_auditlog_entity_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salary',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='contract',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='hrdocument',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='performanceevaluation',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='performanceevaluation',
            name='teacher_acknowledged',
        ),
        migrations.RemoveField(
            model_name='performanceevaluation',
            name='teacher_comments',
        ),

        migrations.AddField(
            model_name='contract',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hrdocument',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr_documents', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='leave',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='performanceevaluation',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='performanceevaluation',
            name='employee_acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='performanceevaluation',
            name='employee_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='salary',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='hr.employee'),
        ),
        migrations.RemoveField(
            model_name='salary',
            name='teacher',
        ),
        migrations.AlterUniqueTogether(
            name='salary',
            unique_together={('employee', 'pay_period_start', 'pay_period_end')},
        ),
    ]
