# Generated by Django 6.0.6 on 2026-09-04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0006_hrdocument_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidateDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("document_type", models.CharField(choices=[("diploma", "Diplôme"), ("certification", "Certification"), ("license", "Licence d'enseignement"), ("id_card", "Pièce d'identité"), ("cv", "CV"), ("other", "Autre")], default="other", max_length=20)),
                ("filename", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="hr/candidates/documents/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("candidate", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="documents", to="hr.candidate")),
            ],
            options={"ordering": ["-created_at"]},
        ),
    ]
