# Generated by Django 6.0.6 on 2026-09-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0007_candidatedocument"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="employee_number",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
