# Generated by Django 6.0.6 on 2026-08-04 06:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0003_initial'),
        ('students', '0005_alter_student_registration_number'),
        ('teachers', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('date_graded', models.DateField(default=django.utils.timezone.now)),
                ('synced', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.student')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades_given', to='teachers.teacher')),
            ],
            options={
                'db_table': 'grades',
            },
        ),
        migrations.CreateModel(
            name='GradeSyncEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('local_uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text="Clé d'idempotence : évite qu'un replay réseau ne crée deux entrées.", unique=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('source', models.CharField(choices=[('local', 'Saisie hors-ligne'), ('remote', 'Saisie en ligne')], max_length=10)),
                ('local_timestamp', models.DateTimeField(help_text="Horodatage de la saisie effective, tel que capturé sur l'appareil du prof.")),
                ('status', models.CharField(choices=[('pending', 'En attente de traitement'), ('applied', 'Appliquée sans conflit'), ('conflict', 'En conflit'), ('discarded', 'Écartée (doublon idempotent)')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.teacher')),
            ],
            options={
                'db_table': 'grade_sync_entries',
            },
        ),
        migrations.CreateModel(
            name='GradeConflict',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('local_version', models.JSONField(help_text="Snapshot de la valeur en attente (l'entrée en conflit).")),
                ('remote_version', models.JSONField(help_text='Snapshot de la valeur actuellement en base.')),
                ('resolution_choice', models.CharField(blank=True, choices=[('local', 'Garder la version locale'), ('remote', 'Garder la version distante'), ('manual_merge', "Valeur saisie manuellement par l'admin")], max_length=15, null=True)),
                ('resolved_value', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='grades.grade')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sync_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conflict', to='grades.gradesyncentry')),
            ],
            options={
                'db_table': 'grade_conflicts',
            },
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['synced'], name='grades_synced_c8aa7b_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['student', 'course'], name='grades_student_c6f53c_idx'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('student', 'course'), name='uniq_grade_per_student_course'),
        ),
        migrations.AddIndex(
            model_name='gradesyncentry',
            index=models.Index(fields=['status'], name='grade_sync__status_2bdbff_idx'),
        ),
        migrations.AddIndex(
            model_name='gradeconflict',
            index=models.Index(fields=['resolution_choice'], name='grade_confl_resolut_026b22_idx'),
        ),
    ]
