# Generated by Django 6.0.6 on 2026-08-05 03:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_initial'),
        ('grades', '0001_initial'),
        ('students', '0005_alter_student_registration_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(help_text='Ex. 2025-2026', max_length=9)),
                ('term', models.CharField(blank=True, max_length=80)),
                ('title', models.CharField(max_length=150)),
                ('evaluation_type', models.CharField(choices=[('quiz', 'Quiz'), ('assignment', 'Devoir'), ('exam', 'Examen'), ('project', 'Projet'), ('oral', 'Oral')], default='assignment', max_length=20)),
                ('coefficient', models.DecimalField(decimal_places=2, default=1, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('evaluation_date', models.DateField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='courses.course')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='students.schoolclass')),
            ],
            options={
                'ordering': ['-evaluation_date', 'title'],
                'constraints': [models.UniqueConstraint(fields=('course', 'school_class', 'academic_year', 'term', 'title'), name='uniq_assessment_per_period')],
            },
        ),
    ]
