# Generated by Django 6.0.6 on 2026-08-05 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_initial'),
        ('grades', '0002_add_assessments'),
        ('students', '0005_alter_student_registration_number'),
        ('teachers', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='grade',
            name='uniq_grade_per_student_course',
        ),
        migrations.RemoveIndex(
            model_name='grade',
            name='grades_student_c6f53c_idx',
        ),
        migrations.AddField(
            model_name='grade',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='grades.assessment'),
        ),
        migrations.AddField(
            model_name='gradesyncentry',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grades.assessment'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['student', 'assessment'], name='grades_student_f2e1b3_idx'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('student', 'assessment'), name='uniq_grade_per_student_assessment'),
        ),
    ]
