# Generated by Django 6.0.6 on 2026-09-04

from decimal import Decimal

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models


def convert_grades_to_out_of_100(apps, schema_editor):
    """Preserve the meaning of existing grades that were stored out of 20."""
    Grade = apps.get_model("grades", "Grade")
    GradeSyncEntry = apps.get_model("grades", "GradeSyncEntry")
    GradeConflict = apps.get_model("grades", "GradeConflict")

    for model in (Grade, GradeSyncEntry):
        for record in model.objects.all().iterator():
            record.value *= 5
            record.save(update_fields=["value"])

    for conflict in GradeConflict.objects.exclude(resolved_value__isnull=True).iterator():
        conflict.resolved_value *= 5
        conflict.save(update_fields=["resolved_value"])

    for conflict in GradeConflict.objects.all().iterator():
        changed = False
        for field_name in ("local_version", "remote_version"):
            version = getattr(conflict, field_name)
            if version and "value" in version:
                version["value"] = str(Decimal(str(version["value"])) * 5)
                changed = True
        if changed:
            conflict.save(update_fields=["local_version", "remote_version"])


def convert_grades_to_out_of_20(apps, schema_editor):
    Grade = apps.get_model("grades", "Grade")
    GradeSyncEntry = apps.get_model("grades", "GradeSyncEntry")
    GradeConflict = apps.get_model("grades", "GradeConflict")

    for model in (Grade, GradeSyncEntry):
        for record in model.objects.all().iterator():
            record.value /= 5
            record.save(update_fields=["value"])

    for conflict in GradeConflict.objects.exclude(resolved_value__isnull=True).iterator():
        conflict.resolved_value /= 5
        conflict.save(update_fields=["resolved_value"])

    for conflict in GradeConflict.objects.all().iterator():
        changed = False
        for field_name in ("local_version", "remote_version"):
            version = getattr(conflict, field_name)
            if version and "value" in version:
                version["value"] = str(Decimal(str(version["value"])) / 5)
                changed = True
        if changed:
            conflict.save(update_fields=["local_version", "remote_version"])


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0003_link_grades_to_assessments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grade",
            name="value",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                validators=[MinValueValidator(0), MaxValueValidator(100)],
            ),
        ),
        migrations.AlterField(
            model_name="gradesyncentry",
            name="value",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                validators=[MinValueValidator(0), MaxValueValidator(100)],
            ),
        ),
        migrations.AlterField(
            model_name="gradeconflict",
            name="resolved_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                validators=[MinValueValidator(0), MaxValueValidator(100)],
            ),
        ),
        migrations.RunPython(convert_grades_to_out_of_100, convert_grades_to_out_of_20),
        migrations.AddConstraint(
            model_name="grade",
            constraint=models.CheckConstraint(
                condition=models.Q(("value__gte", 0), ("value__lte", 100)),
                name="grade_value_between_0_and_100",
            ),
        ),
        migrations.AddConstraint(
            model_name="gradesyncentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("value__gte", 0), ("value__lte", 100)),
                name="grade_sync_value_between_0_and_100",
            ),
        ),
        migrations.AddConstraint(
            model_name="gradeconflict",
            constraint=models.CheckConstraint(
                condition=models.Q(("resolved_value__gte", 0), ("resolved_value__lte", 100)),
                name="resolved_grade_value_between_0_and_100",
            ),
        ),
    ]
