# Generated by Django 6.0.6 on 2026-09-05 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0005_populate_academic_year'),
        ('students', '0006_academicyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='academic_year',
            field=models.ForeignKey(blank=True, help_text='Année académique (ex: 2025-2026)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='students.academicyear', to_field='label'),
        ),
    ]
