# Generated by Django 6.0.6 on 2026-08-01 06:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('is_synced', models.BooleanField(db_index=True, default=False, verbose_name='Synchronisé')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Synchronisé le')),
                ('sync_attempt_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de tentatives de sync')),
                ('last_sync_error', models.TextField(blank=True, verbose_name='Dernière erreur de sync')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Note de 0 à 5', max_digits=3, verbose_name='Note moyenne')),
                ('rating_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de notes')),
                ('teacher_id', models.CharField(max_length=50, unique=True, verbose_name='ID Professeur')),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Temps plein'), ('PART_TIME', 'Temps partiel'), ('CONTRACT', 'Contrat'), ('TEMPORARY', 'Temporaire')], default='FULL_TIME', max_length=50, verbose_name="Type d'emploi")),
                ('hire_date', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'embauche")),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('INACTIVE', 'Inactif'), ('ON_LEAVE', 'En congé'), ('RETIRED', 'Retraité'), ('TERMINATED', 'Renvoyé')], default='ACTIVE', max_length=20, verbose_name='Statut')),
                ('salary_grade', models.CharField(blank=True, max_length=50, verbose_name='Échelon salarial')),
                ('monthly_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salaire mensuel')),
                ('health_insurance_number', models.CharField(blank=True, max_length=100, verbose_name="Numéro d'assurance maladie")),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200, verbose_name="Contact d'urgence")),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, verbose_name="Téléphone d'urgence")),
                ('office_location', models.CharField(blank=True, max_length=200, verbose_name='Bureau/Salle')),
                ('office_phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone bureau')),
                ('bio', models.TextField(blank=True, verbose_name='Biographie')),
            ],
            options={
                'verbose_name': 'Professeur',
                'verbose_name_plural': 'Professeurs',
                'db_table': 'teachers_teacher',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='TeacherAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('is_present', models.BooleanField(default=True, verbose_name='Présent')),
                ('check_in_time', models.TimeField(blank=True, null=True, verbose_name="Heure d'arrivée")),
                ('check_out_time', models.TimeField(blank=True, null=True, verbose_name='Heure de départ')),
                ('absence_type', models.CharField(blank=True, choices=[('SICK', 'Maladie'), ('PERSONAL', 'Raison personnelle'), ('UNPAID', 'Sans autorisation'), ('AUTHORIZED', 'Autorisé'), ('OTHER', 'Autre')], max_length=50, verbose_name="Type d'absence")),
                ('reason', models.TextField(blank=True, verbose_name='Raison')),
                ('document_proof', models.FileField(blank=True, null=True, upload_to='teacher_absence_proofs/%Y/%m/', verbose_name='Justificatif')),
            ],
            options={
                'verbose_name': 'Présence',
                'verbose_name_plural': 'Présences',
                'db_table': 'teachers_attendance',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TeacherCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('name', models.CharField(max_length=300, verbose_name='Nom de la certification')),
                ('issuing_body', models.CharField(max_length=300, verbose_name='Organisme émetteur')),
                ('issue_date', models.DateField(verbose_name="Date d'obtention")),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('credential_id', models.CharField(blank=True, max_length=200, verbose_name="ID d'accréditation")),
                ('credential_url', models.URLField(blank=True, verbose_name='URL de la accréditation')),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
                'db_table': 'teachers_certification',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='TeacherLeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('leave_type', models.CharField(choices=[('ANNUAL', 'Congé annuel'), ('SICK', 'Arrêt maladie'), ('MATERNITY', 'Congé maternité'), ('PATERNITY', 'Congé paternité'), ('PERSONAL', 'Raison personnelle'), ('BEREAVEMENT', 'Deuil'), ('OTHER', 'Autre')], max_length=50, verbose_name='Type de congé')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('reason', models.TextField(verbose_name='Raison')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name="Date d'approbation")),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Raison du rejet')),
            ],
            options={
                'verbose_name': 'Demande de congé',
                'verbose_name_plural': 'Demandes de congé',
                'db_table': 'teachers_leave_request',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='TeacherPerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('review_period', models.CharField(choices=[('MONTHLY', 'Mensuel'), ('QUARTERLY', 'Trimestriel'), ('SEMI_ANNUAL', 'Semestriel'), ('ANNUAL', 'Annuel')], max_length=50, verbose_name="Période d'évaluation")),
                ('review_date', models.DateField(default=django.utils.timezone.localdate, verbose_name="Date d'évaluation")),
                ('teaching_quality', models.IntegerField(default=3, verbose_name="Qualité d'enseignement")),
                ('student_engagement', models.IntegerField(default=3, verbose_name='Engagement des élèves')),
                ('professionalism', models.IntegerField(default=3, verbose_name='Professionnalisme')),
                ('communication', models.IntegerField(default=3, verbose_name='Communication')),
                ('class_management', models.IntegerField(default=3, verbose_name='Gestion de classe')),
                ('overall_rating', models.DecimalField(decimal_places=1, default=3.0, max_digits=3, verbose_name='Note globale')),
                ('comments', models.TextField(blank=True, verbose_name='Commentaires')),
                ('improvement_areas', models.TextField(blank=True, verbose_name="Domaines d'amélioration")),
                ('strengths', models.TextField(blank=True, verbose_name='Forces')),
            ],
            options={
                'verbose_name': 'Évaluation de performance',
                'verbose_name_plural': 'Évaluations de performance',
                'db_table': 'teachers_performance_review',
                'ordering': ['-review_date'],
            },
        ),
        migrations.CreateModel(
            name='TeacherQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('qualification_type', models.CharField(choices=[('BACHELOR', 'Licence'), ('MASTER', 'Master'), ('DOCTORATE', 'Doctorat'), ('DIPLOMA', 'Diplôme'), ('CERTIFICATE', 'Certificat'), ('OTHER', 'Autre')], max_length=50, verbose_name='Type de qualification')),
                ('field_of_study', models.CharField(max_length=200, verbose_name="Domaine d'études")),
                ('institution', models.CharField(max_length=300, verbose_name='Institution')),
                ('graduation_year', models.IntegerField(verbose_name='Année de graduation')),
                ('certification_number', models.CharField(blank=True, max_length=100, verbose_name='Numéro de certification')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name="Date d'expiration")),
            ],
            options={
                'verbose_name': 'Qualification',
                'verbose_name_plural': 'Qualifications',
                'db_table': 'teachers_qualification',
                'ordering': ['-graduation_year'],
            },
        ),
        migrations.CreateModel(
            name='TeacherSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('day_of_week', models.CharField(choices=[('MONDAY', 'Lundi'), ('TUESDAY', 'Mardi'), ('WEDNESDAY', 'Mercredi'), ('THURSDAY', 'Jeudi'), ('FRIDAY', 'Vendredi'), ('SATURDAY', 'Samedi')], max_length=20, verbose_name='Jour')),
                ('start_time', models.TimeField(verbose_name='Heure de début')),
                ('end_time', models.TimeField(verbose_name='Heure de fin')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Salle/Bureau')),
                ('activity', models.CharField(choices=[('TEACHING', 'Enseignement'), ('OFFICE_HOURS', 'Heures de bureau'), ('MEETING', 'Réunion'), ('SUPERVISION', 'Surveillance'), ('OTHER', 'Autre')], default='TEACHING', max_length=200, verbose_name="Type d'activité")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Horaire',
                'verbose_name_plural': 'Horaires',
                'db_table': 'teachers_schedule',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='TeacherSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('subject', models.CharField(max_length=200, verbose_name='Matière/Sujet')),
                ('level', models.CharField(choices=[('KINDERGARTEN', 'Maternelle'), ('PRIMARY', 'Primaire'), ('SECONDARY', 'Secondaire'), ('ALL', 'Tous les niveaux')], max_length=50, verbose_name="Niveau d'enseignement")),
                ('certification_level', models.CharField(choices=[('BASIC', 'Basique'), ('INTERMEDIATE', 'Intermédiaire'), ('ADVANCED', 'Avancé'), ('EXPERT', 'Expert')], default='BASIC', max_length=20, verbose_name='Niveau de certification')),
                ('years_of_experience', models.PositiveIntegerField(default=0, verbose_name="Années d'expérience")),
                ('is_primary', models.BooleanField(default=False, verbose_name='Spécialité principale')),
            ],
            options={
                'verbose_name': 'Spécialité',
                'verbose_name_plural': 'Spécialités',
                'db_table': 'teachers_specialty',
            },
        ),
    ]
