# Generated by Django 6.0.6 on 2026-07-22 02:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherperformancereview',
            name='review_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name="Date d'évaluation"),
        ),
    ]
