# Generated by Django 6.0.6 on 2026-08-01 06:48

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id', models.UUIDField()),
                ('business_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('financial_projection', models.JSONField(blank=True, default=dict, help_text='Projections chiffrées (revenus, coûts...)')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumis'), ('under_review', 'En évaluation'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='draft', max_length=20)),
                ('final_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Business Plan',
                'verbose_name_plural': 'Business Plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('sector', models.CharField(blank=True, max_length=150)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('contact_name', models.CharField(blank=True, max_length=150)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id', models.UUIDField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('ongoing', 'En cours'), ('completed', 'Terminé'), ('terminated', 'Interrompu')], default='pending', max_length=20)),
                ('final_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('certificate_path', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stage',
                'verbose_name_plural': 'Stages',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='InternshipLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('log_date', models.DateField()),
                ('daily_activities', models.TextField()),
                ('challenges', models.TextField(blank=True)),
                ('synced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Journal de stage',
                'verbose_name_plural': 'Journaux de stage',
                'ordering': ['-log_date'],
            },
        ),
        migrations.CreateModel(
            name='Mentorship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id', models.UUIDField()),
                ('start_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Actif'), ('paused', 'En pause'), ('completed', 'Terminé')], default='active', max_length=20)),
                ('objectives', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mentorat',
                'verbose_name_plural': 'Mentorats',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='MentorshipSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_date', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('notes', models.TextField(blank=True)),
                ('feedback', models.TextField(blank=True)),
                ('synced', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Séance de mentorat',
                'verbose_name_plural': 'Séances de mentorat',
                'ordering': ['-session_date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planning', 'Planification'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('evaluated', 'Évalué')], default='planning', max_length=20)),
                ('final_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDeliverable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('due_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('submitted', 'Soumis'), ('late', 'En retard'), ('graded', 'Noté')], default='pending', max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_by_student_id', models.UUIDField(blank=True, null=True)),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('feedback', models.TextField(blank=True)),
                ('synced', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Livrable de projet',
                'verbose_name_plural': 'Livrables de projet',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id', models.UUIDField()),
                ('role', models.CharField(choices=[('leader', 'Chef de projet'), ('member', 'Membre')], default='member', max_length=20)),
                ('contribution', models.TextField(blank=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Membre de projet',
                'verbose_name_plural': 'Membres de projet',
            },
        ),
        migrations.CreateModel(
            name='BusinessPlanPresentation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('presentation_date', models.DateTimeField()),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('evaluator_comments', models.TextField(blank=True)),
                ('business_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to='projects.businessplan')),
            ],
            options={
                'verbose_name': 'Présentation de Business Plan',
                'verbose_name_plural': 'Présentations de Business Plan',
                'ordering': ['-presentation_date'],
            },
        ),
    ]
