# Generated by Django 6.0.6 on 2026-08-01 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0003_initial'),
        ('projects', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessplanpresentation',
            name='evaluator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='internship',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internships', to='projects.company'),
        ),
        migrations.AddField(
            model_name='internship',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentored_internships', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='internshiplog',
            name='internship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='projects.internship'),
        ),
        migrations.AddField(
            model_name='mentorship',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorships', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='mentorshipsession',
            name='mentorship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='projects.mentorship'),
        ),
        migrations.AddField(
            model_name='project',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='courses.course'),
        ),
        migrations.AddField(
            model_name='project',
            name='teacher',
            field=models.ForeignKey(blank=True, help_text='Superviseur du projet', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_projects', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='projectdeliverable',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='projects.project'),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='projects.project'),
        ),
        migrations.AlterUniqueTogether(
            name='internshiplog',
            unique_together={('internship', 'log_date')},
        ),
        migrations.AlterUniqueTogether(
            name='projectmember',
            unique_together={('project', 'student_id')},
        ),
    ]
