# Generated by Django 6.0.6 on 2026-08-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_incubatormentor_businessplan_bearer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='assessment',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
