# Generated by Django 6.0.6 on 2026-08-12 06:30
# Manually edited: these fields were UUIDField in 0001_initial and are being
# switched to BigIntegerField. Postgres has no valid cast between uuid and
# bigint (unlike SQLite, which is untyped and accepted the AlterField as a
# no-op), so a straight AlterField fails with "cannot cast type uuid to
# bigint". Since these are raw id-holder fields (not real ForeignKeys) and
# there is no production data to preserve, we drop and recreate each column
# instead of trying to cast it.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_internship_assessment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessplan',
            name='student_id',
        ),
        migrations.AddField(
            model_name='businessplan',
            name='student_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='internship',
            name='student_id',
        ),
        migrations.AddField(
            model_name='internship',
            name='student_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='mentorship',
            name='student_id',
        ),
        migrations.AddField(
            model_name='mentorship',
            name='student_id',
            field=models.BigIntegerField(),
        ),
        migrations.RemoveField(
            model_name='projectdeliverable',
            name='submitted_by_student_id',
        ),
        migrations.AddField(
            model_name='projectdeliverable',
            name='submitted_by_student_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='projectmember',
            name='student_id',
        ),
        migrations.AddField(
            model_name='projectmember',
            name='student_id',
            field=models.BigIntegerField(),
        ),
    ]