# Generated by Django 6.0.6 on 2026-08-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_internship_assessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessplan',
            name='student_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='student_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mentorship',
            name='student_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='projectdeliverable',
            name='submitted_by_student_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='student_id',
            field=models.BigIntegerField(),
        ),
    ]
