# Generated by Django 6.0.6 on 2026-07-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrateur"),
                    ("DIRECTOR", "Directeur"),
                    ("TEACHER", "Professeur"),
                    ("STUDENT", "Élève"),
                    ("PARENT", "Parent"),
                    ("SECRETARY", "Secrétaire"),
                    ("ACCOUNTANT", "Comptable"),
                    ("STAFF", "Personnel"),
                ],
                default="STUDENT",
                max_length=20,
            ),
        ),
    ]
