# Generated by Django 6.0.6 on 2026-08-01 07:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0003_initial'),
        ('students', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('local_uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text="Généré côté client au moment de la création offline. Sert de clé d'idempotence pour éviter les doublons lors du replay.", unique=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('active', 'Active'), ('suspended', 'Suspendue'), ('validated', 'Validée'), ('rejected', 'Rejetée')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('synced', models.BooleanField(default=True, help_text="False tant que l'enregistrement créé/modifié en local n'a pas été confirmé par le serveur cloud.")),
                ('created_offline', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_inscriptions', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='students.student')),
            ],
            options={
                'db_table': 'inscriptions',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['status'], name='inscription_status_13b497_idx'), models.Index(fields=['synced'], name='inscription_synced_0f7a69_idx'), models.Index(fields=['student', 'course'], name='inscription_student_3dbc5d_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'approved', 'active', 'suspended'])), fields=('student', 'course'), name='uniq_active_inscription_per_student_course')],
            },
        ),
    ]
