# Generated by Django 6.0.6 on 2026-08-03 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_initial'),
        ('enrollments', '0001_initial'),
        ('students', '0004_add_tuition_fee_to_schoolclass'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # SQLite never created the partial index as a real DB constraint,
        # so we update Django state only (database_operations=[]).
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name='inscription',
                    name='uniq_active_inscription_per_student_course',
                ),
            ],
        ),
        migrations.AddField(
            model_name='inscription',
            name='school_class',
            field=models.ForeignKey(
                blank=True,
                help_text="Classe dans laquelle l'\u00e9tudiant s'inscrit. Remplace le champ 'course' au niveau macro.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='inscriptions',
                to='students.schoolclass',
            ),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='course',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='inscriptions',
                to='courses.course',
            ),
        ),
        migrations.AddConstraint(
            model_name='inscription',
            constraint=models.UniqueConstraint(
                condition=models.Q(('status__in', ['pending', 'approved', 'active', 'suspended'])),
                fields=('student', 'school_class'),
                name='uniq_active_inscription_per_student_class',
            ),
        ),
    ]
