# Generated by Django 6.0.6 on 2026-08-05 03:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_initial'),
        ('enrollments', '0002_add_school_class_to_inscription'),
        ('students', '0005_alter_student_registration_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='inscription',
            constraint=models.UniqueConstraint(condition=models.Q(('course__isnull', False), ('status__in', ['pending', 'approved', 'active', 'suspended'])), fields=('student', 'course'), name='uniq_active_inscription_per_student_course'),
        ),
    ]
