# Generated by Django 6.0.6 on 2026-08-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0003_add_course_duplicate_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, help_text='Numéro de dossier auto-généré (ex: PRE-2026-0001).', max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(blank=True, max_length=10)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('telephone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.TextField(blank=True)),
                ('commune', models.CharField(blank=True, max_length=100)),
                ('departement', models.CharField(blank=True, max_length=100)),
                ('programme', models.CharField(blank=True, default='Entrepreneuriat', max_length=200)),
                ('promotion', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('new', 'Nouvelle'), ('reviewed', 'Examinée'), ('converted', 'Convertie en inscription'), ('rejected', 'Rejetée')], default='new', max_length=20)),
                ('notes_admin', models.TextField(blank=True)),
                ('date_inscription', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pre_inscriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
