# Generated by Codex on 2026-09-03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("enrollments", "0004_add_pre_inscription")]

    operations = [
        migrations.AddField(
            model_name="inscription",
            name="promotion",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
