# Generated by Django 6.0.6 on 2026-09-05 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0005_inscription_promotion'),
        ('students', '0006_academicyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='academic_year',
            field=models.ForeignKey(blank=True, help_text="Année académique d'inscription. Si vide, héritée de l'année active.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions', to='students.academicyear'),
        ),
    ]
