# Generated by Django 6.0.6 on 2026-08-01 06:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConflictResolution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conflict_type', models.CharField(choices=[('version_mismatch', 'Versions différentes'), ('deleted_remotely', 'Supprimé côté serveur'), ('duplicate_natural_key', 'Doublon (clé naturelle)')], max_length=30)),
                ('local_version', models.JSONField()),
                ('remote_version', models.JSONField(blank=True, null=True)),
                ('resolution_choice', models.CharField(blank=True, choices=[('local', 'Garder la version locale'), ('remote', 'Garder la version distante'), ('manual_merge', 'Fusion manuelle')], max_length=20)),
                ('merged_data', models.JSONField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Résolution de conflit',
                'verbose_name_plural': 'Résolutions de conflit',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LocalQueueEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=100)),
                ('record_id', models.CharField(blank=True, max_length=100)),
                ('action', models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression')], max_length=10)),
                ('data', models.JSONField()),
                ('local_timestamp', models.DateTimeField()),
                ('client_operation_id', models.CharField(max_length=100, unique=True)),
                ('synced', models.BooleanField(default=False)),
                ('has_conflict', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Entrée de queue locale',
                'verbose_name_plural': 'Entrées de queue locale',
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('success', 'Succès'), ('failed', 'Échoué')], max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Journal de synchronisation',
                'verbose_name_plural': 'Journaux de synchronisation',
                'ordering': ['-logged_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_type', models.CharField(choices=[('insert', 'Création'), ('update', 'Modification'), ('delete', 'Suppression')], max_length=10)),
                ('table_name', models.CharField(max_length=100)),
                ('record_id', models.CharField(blank=True, max_length=100)),
                ('conflict_status', models.CharField(choices=[('pending', 'En attente'), ('conflict', 'Conflit'), ('resolved', 'Résolu'), ('synced', 'Synchronisé'), ('failed', 'Échoué')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Opération de synchronisation',
                'verbose_name_plural': 'Opérations de synchronisation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_name', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'En pause'), ('completed', 'Terminée')], default='active', max_length=20)),
                ('total_operations', models.PositiveIntegerField(default=0)),
                ('operations_completed', models.PositiveIntegerField(default=0)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'File de synchronisation',
                'verbose_name_plural': 'Files de synchronisation',
            },
        ),
    ]
