# Generated by Django 6.0.6 on 2026-08-01 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sync', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conflictresolution',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_conflicts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='syncoperation',
            name='initiated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_operations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='synclog',
            name='sync_operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='sync.syncoperation'),
        ),
        migrations.AddField(
            model_name='localqueueentry',
            name='sync_operation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entry', to='sync.syncoperation'),
        ),
        migrations.AddField(
            model_name='conflictresolution',
            name='sync_operation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conflict', to='sync.syncoperation'),
        ),
        migrations.AddField(
            model_name='syncoperation',
            name='queue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='sync.syncqueue'),
        ),
        migrations.AddIndex(
            model_name='localqueueentry',
            index=models.Index(fields=['synced'], name='sync_localq_synced_e05456_idx'),
        ),
        migrations.AddIndex(
            model_name='localqueueentry',
            index=models.Index(fields=['has_conflict'], name='sync_localq_has_con_eb9055_idx'),
        ),
        migrations.AddIndex(
            model_name='syncoperation',
            index=models.Index(fields=['conflict_status'], name='sync_syncop_conflic_ef4c2e_idx'),
        ),
        migrations.AddIndex(
            model_name='syncoperation',
            index=models.Index(fields=['table_name', 'record_id'], name='sync_syncop_table_n_4fe205_idx'),
        ),
    ]
