# Generated by Django 6.0.6 on 2026-07-22 10:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("enrollments", "__first__"),
        ("students", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("stripe", "Carte bancaire (Stripe)"),
                            ("paypal", "PayPal"),
                            ("mobile_money", "Mobile Money"),
                            ("bank_transfer", "Virement bancaire"),
                            ("cash", "Espèces"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_online",
                    models.BooleanField(
                        default=True,
                        help_text="False pour les méthodes nécessitant une confirmation manuelle (espèces, virement) — utilisables même sans passerelle en ligne.",
                    ),
                ),
                ("public_config", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Moyen de paiement",
                "verbose_name_plural": "Moyens de paiement",
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(editable=False, max_length=30, unique=True),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("currency", models.CharField(default="HTG", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("partially_paid", "Partiellement payée"),
                            ("paid", "Payée"),
                            ("overdue", "En retard"),
                            ("cancelled", "Annulée"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateField()),
                ("issued_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "inscription",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice",
                        to="enrollments.inscription",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facture",
                "verbose_name_plural": "Factures",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="HTG", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("processing", "En cours"),
                            ("completed", "Complété"),
                            ("failed", "Échoué"),
                            ("refunded", "Remboursé"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "gateway_reference",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("idempotency_key", models.CharField(max_length=100, unique=True)),
                ("failure_reason", models.TextField(blank=True)),
                ("synced", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "initiated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments_initiated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="finance.invoice",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="students.student",
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="finance.paymentmethod",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement",
                "verbose_name_plural": "Paiements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "receipt_number",
                    models.CharField(editable=False, max_length=30, unique=True),
                ),
                ("pdf_path", models.CharField(blank=True, max_length=500)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipt",
                        to="finance.payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reçu",
                "verbose_name_plural": "Reçus",
            },
        ),
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("stripe", "Stripe"),
                            ("paypal", "PayPal"),
                            ("mobile_money", "Mobile Money"),
                        ],
                        max_length=20,
                    ),
                ),
                ("external_event_id", models.CharField(max_length=255)),
                ("payload", models.JSONField()),
                ("processed", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Événement Webhook",
                "verbose_name_plural": "Événements Webhook",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "external_event_id"),
                        name="uniq_provider_event",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["status"], name="finance_inv_status_d9b47e_idx"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["student", "status"], name="finance_inv_student_96f21e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["status"], name="finance_pay_status_cb601d_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["synced"], name="finance_pay_synced_6e4f72_idx"),
        ),
    ]
