# Generated by Django 6.0.6 on 2026-08-04 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_fix_moncash_natcash_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='code',
            field=models.CharField(choices=[('moncash', 'MonCash'), ('natcash', 'NatCash'), ('bank_transfer', 'Virement bancaire'), ('cash', 'Espèces'), ('mobile_money', 'Mobile Money'), ('stripe', 'Carte bancaire (Stripe)'), ('paypal', 'PayPal')], max_length=20, unique=True),
        ),
    ]
