# Generated by Django 6.0.6 on 2026-09-04 04:50 (modified to handle existing rows)

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify
import uuid


def generate_slugs(apps, schema_editor):
    Article = apps.get_model("media_center", "Article")
    seen = set()
    for article in Article.objects.all():
        base = slugify(article.title) or "article"
        candidate = base
        while candidate in seen or Article.objects.filter(slug=candidate).exclude(pk=article.pk).exists():
            candidate = base + "-" + str(uuid.uuid4())[:8]
        article.slug = candidate
        article.save(update_fields=["slug"])
        seen.add(candidate)


class Migration(migrations.Migration):

    dependencies = [
        ("media_center", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="comments_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="article",
            name="shares_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="article",
            name="views_count",
            field=models.PositiveIntegerField(default=0),
        ),
        # Add slug WITHOUT unique=True so existing rows can be populated
        migrations.AddField(
            model_name="article",
            name="slug",
            field=models.SlugField(max_length=280, blank=True, default=""),
            preserve_default=False,
        ),
        # Fill slugs for existing rows
        migrations.RunPython(generate_slugs, migrations.RunPython.noop),
        # Now enforce uniqueness
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(max_length=280, blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="category",
            field=models.CharField(choices=[("news","Actualites"),("communication","Communiques"),("event","Evenements"),("entrepreneurship","Entrepreneuriat"),("innovation","Innovation"),("testimonial","Temoignages"),("partnership","Partenariats"),("student_life","Vie estudiantine"),("success","Reussites"),("training","Formations")], default="news", max_length=30),
        ),
        migrations.AlterField(
            model_name="article",
            name="status",
            field=models.CharField(choices=[("draft","Brouillon"),("published","Publie"),("archived","Archive"),("scheduled","Programme")], default="draft", max_length=20),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("author_name", models.CharField(max_length=150)),
                ("author_email", models.EmailField(blank=True, max_length=254)),
                ("content", models.TextField()),
                ("is_approved", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("article", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="comments", to="media_center.article")),
            ],
            options={
                "verbose_name": "Commentaire",
                "verbose_name_plural": "Commentaires",
                "ordering": ["-created_at"],
            },
        ),
    ]
