# Generated by Django 6.0.6 on 2026-09-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("media_center", "0002_article_comments_count_article_shares_count_and_more")]

    operations = [
        migrations.AddField(model_name="mediaasset", name="album", field=models.CharField(blank=True, max_length=150)),
        migrations.AddField(model_name="mediaasset", name="promotion", field=models.CharField(blank=True, max_length=50)),
        migrations.AddField(model_name="article", name="gallery", field=models.ManyToManyField(blank=True, related_name="article_galleries", to="media_center.mediaasset")),
    ]
