# Generated by Django 6.0.6 on 2026-08-01 06:48

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Ex: DEV-WEB-101', max_length=30, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('duration_weeks', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('capacity_max', models.PositiveIntegerField(default=30, help_text="Nombre max d'étudiants inscrits")),
                ('fees_amount', models.DecimalField(decimal_places=2, help_text="Montant utilisé par l'app Finance pour générer la facture", max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('active', 'Actif'), ('archived', 'Archivé')], default='draft', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('synced', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CourseCoTeacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Co-intervenant',
                'verbose_name_plural': 'Co-intervenants',
            },
        ),
        migrations.CreateModel(
            name='CoursePrerequisite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Prérequis',
                'verbose_name_plural': 'Prérequis',
            },
        ),
        migrations.CreateModel(
            name='CourseSyllabusVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('media_file_id', models.UUIDField(blank=True, help_text='Référence vers MEDIA_FILES', null=True)),
                ('notes', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Version de syllabus',
                'verbose_name_plural': 'Versions de syllabus',
                'ordering': ['-version_number'],
            },
        ),
    ]
