# Generated by Django 6.0.6 on 2026-08-01 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, help_text='Professeur responsable du cours', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_taught', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='coursecoteacher',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_teachers', to='courses.course'),
        ),
        migrations.AddField(
            model_name='coursecoteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_taught_courses', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='courseprerequisite',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='courses.course'),
        ),
        migrations.AddField(
            model_name='courseprerequisite',
            name='required_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_prerequisite_for', to='courses.course'),
        ),
        migrations.AddField(
            model_name='coursesyllabusversion',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_versions', to='courses.course'),
        ),
        migrations.AlterUniqueTogether(
            name='coursecoteacher',
            unique_together={('course', 'teacher')},
        ),
        migrations.AlterUniqueTogether(
            name='courseprerequisite',
            unique_together={('course', 'required_course')},
        ),
        migrations.AlterUniqueTogether(
            name='coursesyllabusversion',
            unique_together={('course', 'version_number')},
        ),
    ]
