# Generated by Django 6.0.6 on 2026-08-02 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolClass",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=150)),
                ("level", models.PositiveSmallIntegerField(default=1)),
                ("room", models.CharField(blank=True, max_length=50)),
                ("capacity", models.PositiveSmallIntegerField(default=30)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "specialization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classes",
                        to="students.specialization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Classe",
                "verbose_name_plural": "Classes",
                "ordering": ["specialization__name", "level"],
                "unique_together": {("specialization", "level")},
            },
        ),
        migrations.AddField(
            model_name="student",
            name="school_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="students",
                to="students.schoolclass",
            ),
        ),
    ]
