# Generated by Django 6.0.6 on 2026-08-03 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_schoolclass_student_school_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='tuition_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Frais de scolarité pour cette classe. Utilisé pour générer la facture à l'inscription.", max_digits=10),
        ),
    ]
