# Generated by Django 6.0.6 on 2026-08-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_add_tuition_fee_to_schoolclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='registration_number',
            field=models.CharField(editable=False, max_length=30),
        ),
    ]
