# Generated by Django 6.0.6 on 2026-08-04 06:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0005_alter_student_registration_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(choices=[('HTG', 'Gourde haïtienne'), ('USD', 'Dollar américain')], default='HTG', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit Card'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('other', 'Other')], default='other', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=255)),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='payments/receipts/')),
                ('synced', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_payments', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('student', 'transaction_id')},
            },
        ),
    ]
